C:\Users\coolm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\utils\data\dataloader.py:557: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 8 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
C:\Users\coolm\AppData\Local\Temp\ipykernel_29200\1507249952.py:51: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.log_softmax(x)
Unsupported operator aten::tanh encountered 3 time(s)
Unsupported operator aten::ones_like encountered 9 time(s)
Unsupported operator aten::mul encountered 18 time(s)
Unsupported operator aten::add encountered 9 time(s)
Unsupported operator aten::log_softmax encountered 1 time(s)
Total trainable parameters of VietaPell: 105856
FLOPs of VietaPell: 106046.0
Training:   0%|          | 0/938 [00:00<?, ?it/s]C:\Users\coolm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\utils\data\dataloader.py:557: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 8 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
C:\Users\coolm\AppData\Local\Temp\ipykernel_29200\1507249952.py:51: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.log_softmax(x)
Training: 100%|██████████| 938/938 [00:36<00:00, 25.81it/s, Loss=1.7, Acc=37.6] 
Epoch 1/50:
Train Loss: 1.6916, Train Acc: 0.3755
Test Loss: 0.5450, Test Acc: 0.8405
Training: 100%|██████████| 938/938 [00:35<00:00, 26.16it/s, Loss=0.631, Acc=79.9]
Epoch 2/50:
Train Loss: 0.6270, Train Acc: 0.7987
Test Loss: 0.3552, Test Acc: 0.8954
Training: 100%|██████████| 938/938 [00:49<00:00, 18.84it/s, Loss=0.431, Acc=86.5]
Epoch 3/50:
Train Loss: 0.4306, Train Acc: 0.8650
Test Loss: 0.2553, Test Acc: 0.9237
Training: 100%|██████████| 938/938 [00:34<00:00, 27.48it/s, Loss=0.366, Acc=88.6]
Epoch 4/50:
Train Loss: 0.3661, Train Acc: 0.8859
Test Loss: 0.2051, Test Acc: 0.9382
Training: 100%|██████████| 938/938 [00:30<00:00, 30.84it/s, Loss=0.322, Acc=89.9]
Epoch 5/50:
Train Loss: 0.3203, Train Acc: 0.8993
Test Loss: 0.1826, Test Acc: 0.9434
Training: 100%|██████████| 938/938 [00:51<00:00, 18.26it/s, Loss=0.304, Acc=90.5]
Epoch 6/50:
Train Loss: 0.3014, Train Acc: 0.9049
Test Loss: 0.1618, Test Acc: 0.9492
Training: 100%|██████████| 938/938 [00:52<00:00, 17.96it/s, Loss=0.281, Acc=91.2]
Epoch 7/50:
Train Loss: 0.2802, Train Acc: 0.9119
Test Loss: 0.1714, Test Acc: 0.9448
Training: 100%|██████████| 938/938 [00:56<00:00, 16.49it/s, Loss=0.27, Acc=91.5] 
Epoch 8/50:
Train Loss: 0.2691, Train Acc: 0.9150
Test Loss: 0.1644, Test Acc: 0.9485
Training:  71%|███████   | 665/938 [00:52<00:21, 12.66it/s, Loss=0.266, Acc=91.7]
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x000001F1820797E0>
Traceback (most recent call last):
  File "C:\Users\coolm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\utils\data\dataloader.py", line 1477, in __del__
    self._shutdown_workers()
  File "C:\Users\coolm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\utils\data\dataloader.py", line 1435, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
